### ISSUE TITLE
zc158, php 8.1: multiple PHP Deprecated errors: Return type of Illuminate\Container\Container::offsetExists($key) 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4512]
a lot of similar deprecated messages occur with php 8.1, with both admin and shopfront
for example
```
--> PHP Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in...
\laravel\vendor\illuminate\container\Container.php on line 1352.
```

**Comment by scottcwilson** [comment]
Good to know, but bear in mind that 1.5.8 might only be good up to PHP 8.0.  (This is the current max PHP level noted in the documentation.)

**Comment by torvista** [comment]
A quick navigate around a few  pages didn't add anything to this bunch of debugs, so there may well be little to fix.
If someone fixes this, I'll continue to use 8.1 locally, see if anything else crops up. Otherwise I'll continue using 8 and we'll be none the wiser for the moment.

**Comment by scottcwilson** [comment]
Please do keep logging 8.1 issues since we'll have to fix those at some point too.  Thanks.

**Comment by mc12345678** [comment]
Couple of questions on this.
1) @torvista , in which specific php 8.1.x version was/is this identified?
2) (Whomever): considering that Zen Cart V1.5.8 is expected to support no lower than php 7.3, what are the thoughts on including return type declarations?

Background for 2) there are two ways identified to address/resolve this particular notice. Either provide the return type(s) that match the original method or identify to basically ignore the return type because it is in some sort of transition...

Unfortunately, it does not appear that PHP is able to fully evaluate the actual returned content to state what type(s) it is. In this case, bool is the only type of data returned regardless the options within the return that evaluate to other than `false` (i.e. `true`). It appears that the php code parsing is specifically looking for the method to have a return type that matches the original method that is being overridden. It is not looking at the content of what is returned...

Such return type declaration was added in PHP 7. Sure there are some return types available in php 7.1, 7.2 and 8.0 that are not available in 7.0, but supporting those "earlier" versions may be possible by ignoring the return type (where absolutely necessary to support backwards compatibility). It is for this reason I ask what consideration there is for earlier PHP versions and/or how strict the lower/lowest php limit is being set... The decision/permission makes a difference on the method of resolution. I personally think that the right thing is to declare the return type of this overridden method (and others that are so specifically identified in the core php code) rather than "ignoring" the condition.

**Comment by torvista** [comment]
It happens on 8.1.0, 8.1.1 which is all I have installed.

**Comment by mc12345678** [comment]
> It happens on 8.1.0, 8.1.1 which is all I have installed.

Thanks, I initially asked the question of specific version after an initial code review of PHP source, but then have found additional information that confirmed my above statement which also matches the notice message provided. 

I was really trying to find the specific code that provided that message to see if there was a possible (more complicated) means to evaluate the content being returned instead of the method having a signature that matches the original code.  It appears though that the solution incorporated and possibly going forwards is when the method is expected to have a directly matching signature, either make sure it is matched or add a comment type tag that will allow it to silently be processed. In this way an earlier php version that does not have the requirement will continue to process without issue and when the signature is expected the comment is evaluated to ignore the "requirement". The only real issue is if the return type is provided in the signature ***and*** an older version of php is used (that doesn't recognize return types (<= PHP 5.x and some specific types are not recognized below 8.0)) that is when the code/operation fails.

As long as there is continued agreement that php 7.0 would be the expected/permitted minimum, then return types could be incorporated. If not, then the comment (with possible additional indication of expected return type for future incorporation) would be the suggested avenue of attack.

**Comment by scottcwilson** [comment]
> As long as there is continued agreement that [PHP 7.3] would be the expected/permitted minimum ...

Yes, PHP 7.3 is the minimum for Zen Cart 1.5.8.

**Comment by g2ktcf** [comment]
> > As long as there is continued agreement that [PHP 7.3] would be the expected/permitted minimum ...
> 
> Yes, PHP 7.3 is the minimum for Zen Cart 1.5.8.

![image](https://user-images.githubusercontent.com/3268361/148217438-a3563ec2-f311-4a50-b7b8-a994f9c28bc9.png)


Even 7.3 is questionable in my view as it is now listed as EOL.

**Comment by scottcwilson** [comment]
7.3 is supported so that you can upgrade a live site running Zen Cart 1.5.6/7 without too much downtime.  It's not recommended for running once the upgrade is complete.

**Comment by mc12345678** [comment]
FYI, I did some more research. Because the mixed type was not incorporated until php 8 and one of the other methods returns a type that doesn't match the method definition (I haven't yet looked to see how that particular type plays into the mix yet), the comment that causes ignoring the notice was incorporated into the Laravel code in a version more recent than what has been incorporated to Zen Cart as of yet. 

So as I understand it then, the point of the vendor code and or laravel directory is for that software to be dropped in without unique modifications to support or particular operations. An I right or wrong about that? The reason I ask is because either the Zen Cart version of the code is updated to specifically address this particular issue or the laravel code in the distribution is updated to align with what has been done in the bigger project...

**Comment by scottcwilson** [comment]
> So as I understand it then, the point of the vendor code and or laravel directory is for that software to be dropped in 
> without unique modifications to support or particular operations. 

That's the dream.  Of course as you point out, the Zen Cart software still has to be upgraded in lockstep with 3rd party code - it's not a mix or match proposition.

**Comment by proseLA** [comment]
ok, lot of interesting information here.  i have done some rudimentary testing in my suito innocuous way.  this is my preliminary information on this problem:

- my composer foo is not that strong.  and running composer update from within the laravel directory did not give me any worthy results to report on.
- as i was not involved in this laravel directory (but of which i am a fan), doing a true plug in from laravel would not seem to work.  there are some minor lower case v sentence case differences in directory names/structures.
- i did do a fresh laravel install on a test system; and then copied over the directories that we are using within the laravel directory and named then according to the current naming in ZC.
- these new files seemed to have resolved the errors seem on php 8.1.  in addition, they run without error on php 7.4.
- php 7.3, on the other hand, causes system crashes.  the following error gets logged numerous times into the apache log:
```
AH00052: child pid 6127 exit signal Segmentation fault (11)
```
- from my limited understanding, we were using laravel to implement something similar to the zc_plugins on the admin side for the storefront.  i have done no testing on any thing of any nature associated with that.

based on the information contained in this thread, i thought it might be an interesting avenue to purse to resolve these errors, so i felt like sharing it here.  i will continue to use my new updated laravel directory and see what other problems might arise.

**Comment by scottcwilson** [comment]
I was hoping some nice person would step forward and fix this.  It sure is annoying!

**Comment by torvista** [comment]
And this

https://github.com/zencart/zencart/issues/4270

I don't think there is a shortage of nice people. But there is a shortage of Laravel people, methinks.

**Comment by scottcwilson** [comment]
I'd love to have 158 support 8.1 if possible.  I just don't know how much work is involved.

**Comment by mc12345678** [comment]
> I don't think there is much to do, outside of massaging the Laravel setup.

Which in the laravel software has predominantly been to effectively silence many of the items that have been identified here as troubling. That appears to have been done largely to support backwards compatibility by those working on the project.

**Comment by proseLA** [comment]
support for 8.1 also requires the removal of the deprecated `strftime` function.  i proposed a class file for replacement but no opinions on that methodology.

**Comment by zcwilt** [comment]
`I don't think there is much to do, outside of massaging the Laravel setup`

This is exactly right. The laravel code hasn't been updated since it was first introduced

I'll look to fox this over the weekend

**Comment by proseLA** [comment]
@zcwilt a while back,  i did a little playing.  this works under 8.1 but chokes under 7.4:

https://github.com/proseLA/zencart/tree/laravel-8.1-fixes

really do not have enough time to look deeper, but if helps you out at all, feel free to take as necessary.

it also includes my `zcDate` class to address the `strftime` problems.

**Comment by lat9** [comment]
> I don't think there is much to do, outside of massaging the Laravel setup.

See #4449 for an exhaustive list that @drbyte created.

**Comment by lat9** [comment]
@zcwilt, this _really_, **_really_** needs to be fixed.  It's a PITA when testing with PHP 8.1 and later.

**Comment by lat9** [comment]
This appears to have been corrected via PR #4781, @torvista and @proseLA would you also verify.  If you agree, we can close this issue.

**Comment by proseLA** [comment]
this issue looks resolved, however, if you now try running php 7.4, you will get the following output to your browser:
```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".
```

**Comment by scottcwilson** [comment]
@proseLA Ian is aware of this issue and is working on it.  We'll keep this ticket open until the dependency issue is resolved.

**Comment by zcwilt** [comment]
The problem here is, that to fix the deprecation errors I had to update Laravel components to the v9 branch.
This has a minimum requirement of php 8.0.2. 

There are two solutions.

Use 2 vendor directories and choose the one to use in application_bootstrap depending on php versions
This would leave us getting the deprecation errors for any one using <php8

The other option is to remove Laravel dependencies altogether.
The downside here is that would require a major refactor of the plugin manager code.

Still debating this.

**Comment by zcwilt** [comment]
Also third option.
I did try just updating to the 8.0 branch for Laravel, but was still seeing deprecation errors.
I guess we could us e8.0 which would support 7.4 and see if I Can manually fix the remaining deprecation errors.
It depends here on how deep contract/interface changes need to be addressed to fix the return type problems.
Will try this later today.

**Comment by scottcwilson** [comment]
@torvista  Can this be closed?  I think the issue is fixed.
